Models/DropDownMDL.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Point_of_Sales.Models
{
    public class DropDownMDL
    {
        public int ID { get; set; }
        public string Value { get; set; }
    }
}

Models/InvoiceMDL.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Point_of_Sales.Models
{
    public class InvoiceMDL
    {
        public Int64 PK_InvoiceId { get; set; }
        public string TotalAmount { get; set; }
        public string SubTotal { get; set; }
        public string VAT { get; set; }
        public string Discount { get; set; }
        public string InvoiceDate { get; set; }
        public int EmployeeId { get; set; }
        public string BillDate { get; set; }
        public List<InvoiceDetails> Detail { get; set; }
    }
    public class InvoiceDetails
    {
        public Int64 PK_Det_Invoice { get; set; }
        public string ProductId { get; set; }
        public string Quantity { get; set; }
        public string ProductName { get; set; }
        public string ItemPrice { get; set; }
    }
}

Models/LoginModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Point_of_Sales.Models
{
    public class LoginModel
    {
        public string UserName { get; set; }
        public string Password { get; set; }
    }

    public class LoginResponse
    {
        public string Status { get; set; }
        public string Message { get; set; }
    }
}

Models/MessageMDL.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Point_of_Sales.Models
{
    public class MessageMDL
    {
        public int MessageId { get; set; }
        public string Message { get; set; }

    }
}

Models/ProductMDL.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Point_of_Sales.Models
{
    public class ProductMDL
    {
        public int PK_ItemId { get; set; }
        [Required(ErrorMessage = "Please Enter Item Name")]
        public string ItemName { get; set; }
        [Required(ErrorMessage = "Please Enter Item Code")]
        public string ItemPrice { get; set; }
        public string ItemCategory { get; set; }
        [Required(ErrorMessage = "Please Select Item Category")]
        public string CategoryName { get; set; }
        public string PurchasePrice { get; set; }
        [Required(ErrorMessage = "Please Enter Quantity")]
        public string OpeningQuantity { get; set; }
        public string Description { get; set; }
        public string StockValue { get; set; }
        public HttpPostedFileBase ProductImage { get; set; }
        public string ProductImageName { get; set; }
    }
}

Models/SaleRequestMDL.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Point_of_Sales.Models
{
    public class SaleRequestMDL
    {
        public int EmployeeId { get; set; }
        public string TotalAmount { get; set; }
        public string SubTotal { get; set; }
        public string VAT { get; set; }
      //  public string InvoiceDate { get; set; }
   
        public string Quantity { get; set; }
        public string ProductId { get; set; }
        public string Discount { get; set; }

    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Point_of_Sales.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View("Login");
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }












        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Controllers/LoginController.cs
using Point_of_Sales.Models;
using System;
using System.Collections.Generic;
using System.IdentityModel.Tokens.Jwt;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Security.Claims;
using System.Web.Http;

namespace Point_of_Sales.Controllers
{
    public class LoginController : ApiController
    {
      

        [Authorize]
        [HttpGet]
        [Route("Login/Get")]
        public IEnumerable<string> Get()
        {
            return new string[] { "value1", "value2" };
        }

        [HttpPost]
        [Route("Login/UserLogin")]
        public IHttpActionResult UserLogin([FromBody]LoginModel objVM)
        {
            var UserList = new List<LoginModel>();
            var user = new LoginModel();
            user.UserName = "shivi";
            user.Password = "123";
            UserList.Add(user);
            var objlist = UserList.FirstOrDefault(x => x.UserName == objVM.UserName && x.Password == objVM.Password);
            if (objlist==null) {
                string path = System.Configuration.ConfigurationManager.AppSettings["path"];
                string url = path +"/Home/Index";

                System.Uri uri = new System.Uri(url);

                return Redirect(uri);
            }
            else
            {
               string Message = createToken(objVM.UserName);
                string path = System.Configuration.ConfigurationManager.AppSettings["path"];
                string url = path  + "/Product/Index";

                System.Uri uri = new System.Uri(url);

                return Redirect(uri);
            }
            //if (objlist == null)
            //{
            //    var response = Request.CreateResponse(OK(), new LoginResponse
            //    {
            //        Status = "Invalid",
            //        Message = "Invalid User."
            //    });
            //    //return
            //}
            //else return new LoginResponse
            //{
            //    Status = "Success",
            //    Message = createToken(objVM.UserName)
            //};
           
        }

        private string createToken(string username)
        {
            //Set issued at date
            DateTime issuedAt = DateTime.UtcNow;
            //set the time when it expires
            DateTime expires = DateTime.UtcNow.AddDays(7);

            var tokenHandler = new JwtSecurityTokenHandler();

            //create a identity and add claims to the user which we want to log in
            ClaimsIdentity claimsIdentity = new ClaimsIdentity(new[]
            {
                new Claim(ClaimTypes.Name, username)
            });

            const string sec = "ERMN05OPLoDvbTTa/QkqLNMI7cPLguaRyHzyg7n5qNBVjQmtBhz4SzYh4NBVCXi3KJHlSXKP+oi2+bXr6CUYTR==";
            var now = DateTime.UtcNow;
            var securityKey = new Microsoft.IdentityModel.Tokens.SymmetricSecurityKey(System.Text.Encoding.Default.GetBytes(sec));
            var signingCredentials = new Microsoft.IdentityModel.Tokens.SigningCredentials(securityKey, Microsoft.IdentityModel.Tokens.SecurityAlgorithms.HmacSha256Signature);


            //create the jwt
            var token = (JwtSecurityToken)
                    tokenHandler.CreateJwtSecurityToken(issuer: "http://localhost:50191", audience: "http://localhost:50191",
                        subject: claimsIdentity, notBefore: issuedAt, expires: expires, signingCredentials: signingCredentials);
            var tokenString = tokenHandler.WriteToken(token);
            return tokenString;
        }
    }
}

Controllers/ProductController.cs
using Point_of_Sales.Models;
using Point_of_Sales.ServicesData;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Point_of_Sales.Controllers
{
    public class ProductController : Controller
    {
        // GET: Product
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult AddEditProduct(int id = 0)
        {
            //ViewData["CategoryList"] = GetCategory();
            if (id != 0)
            {
                ProductServices obj = new ProductServices();
             List<ProductMDL>_list =  obj.GetProductDetails(id,"","");
               // _ItemList = GetItemDetalis(id, "", "");
                return View("AddEditProduct",_list[0]);
            }
            else
            {
                return View();

            }
        }
        
    }
}

Controllers/StoreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Point_of_Sales.Controllers
{
    public class StoreController : Controller
    {
        // GET: Store
        public ActionResult Index()
        {
            return View();
        }
    }
}

Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Views/Home/Login.cshtml
@model Point_of_Sales.Models.LoginModel
@{
    ViewBag.Title = "Index";
}
<div class="row jumbotron">
    <div class="col-lg-8">
        <img style="width:100%;height:700px" src="~/Images/FlyMind.jpg" alt="Italian Trulli">

    </div>
    <div class="col-md-4">
        <div class="jumbotron" style="background-color:lightblue; height:600px !important">
            @using (Html.BeginForm("UserLogin", "LogIn",
           FormMethod.Post, new { @class = "form-horizontal" }))
            {
                @Html.AntiForgeryToken()
                <div class="card m-0">
                    <div class="card-content">
                        <div class="card-body">
                            <form class="form-horizontal" action="" novalidate>
                                <h2 style="color:Red">LogIn</h2>

                                @*<p>@MFTSLanguages.LocalResources.Resource.LoginHeaderName</p>*@

                                <div class="form-group col-md-12">

                                    @Html.TextBoxFor(E => E.UserName, new { @class = "form-control input-md", @placeholder = "User Name", @maxlength = "30", })
                                    @Html.ValidationMessageFor(E => E.UserName)
                                    @*<input type="text" class="form-control input-lg" id="user-name" placeholder="@MFTSLanguages.LocalResources.Resource.YourUserID">*@

                                    <div class="form-control-position">
                                        <i class="la la-user"></i>
                                    </div>
                                </div>
                                <div class="form-group col-md-12">
                                    @*<input type="password" class="form-control input-lg" id="user-password" placeholder= "@MFTSLanguages.LocalResources.Resource.Password" >*@
                                    @Html.PasswordFor(E => E.Password, new { @class = "form-control input-md", @placeholder = "Password" })
                                    @Html.ValidationMessageFor(E => E.Password)
                                    <div class="form-control-position">
                                        <i class="la la-key"></i>
                                    </div>
                                </div>
                                <strong>@TempData["LoginMessage"]</strong>


                                <div class="form-group row">
                                    <div class="col-md-12">
                                        <button type="submit" class="btn btn-success"> Login </button>
                                    </div>
                                </div>

                            </form>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>
@section scripts{
    @Scripts.Render("~/bundles/jqueryval")

    <script type="text/javascript">

        $(document).ready(function () {

        });

    </script>
}

Views/Product/AddEditProduct.cshtml
@model Point_of_Sales.Models.ProductMDL
@{
    ViewBag.Title = "AddEditProduct";
}

<div class="section-body">
    <div class="container-fluid contentHeightShow">
        <div class="panel panel-default">
            <div class="panel-heading">
                <div class="textHead"><h2><strong>Entry Product</strong></h2></div>


            </div>
            <div class="panel-body">
               
                    @Html.HiddenFor(E => E.PK_ItemId)
                    <div class="form-horizontal">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="control-label col-md-4" for="inputEmail">Item Name<span class="red">*</span></label>
                                    <div class="col-md-8">
                                        <div class="dateView">
                                            @Html.TextBoxFor(E => E.ItemName, new { @class = "form-control", @placeholder = "Item Name" })
                                            @Html.ValidationMessageFor(E => E.ItemName)
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="control-label col-md-4" for="inputEmail">Price<span class="red">*</span></label>
                                    <div class="col-md-8">
                                        <div class="dateView">
                                            @Html.TextBoxFor(E => E.ItemPrice, new { @class = "form-control", @placeholder = "Item Price" })
                                            @Html.ValidationMessageFor(E => E.ItemPrice)
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="control-label col-md-4" for="inputEmail">Quantity<span class="red">*</span></label>
                                    <div class="col-md-8">
                                        <div class="dateView">
                                            @Html.TextBoxFor(E => E.OpeningQuantity, new { @class = "form-control", @placeholder = "Quantity" })
                                            @Html.ValidationMessageFor(E => E.ItemPrice)
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="control-label col-md-4" for="inputEmail">Product Image<span class="red">*</span></label>
                                    <div class="col-md-8">
                                        @Html.DisplayFor(E=>E.ProductImageName)
                                        <input type="file" id="fileupload" class="form-control" />
                                    </div>
                                </div>
                            <div class="form-group">
                                <label class="control-label col-md-4" for="inputEmail">Category<span class="red">*</span></label>
                                <div class="col-md-8">
                                    @Html.DropDownListFor(E=>E.CategoryName, new List<SelectListItem>

                                                    {
                                                       new SelectListItem{ Text="Clothing", Value = "Clothing" },
                                                       new SelectListItem{ Text="computers", Value = "computers" },
                                                       new SelectListItem{ Text="Fruits", Value = "Fruits" },
                                                      new SelectListItem{ Text="servicing", Value = "servicing" },
                                                       new SelectListItem{ Text="burger", Value = "burger" },
                                                       new SelectListItem{ Text="pizza", Value = "pizza" }

                                                    },new { @class="form-control"})
                                    @Html.ValidationMessageFor(E => E.CategoryName)
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="control-label col-md-4" for="inputEmail">Description<span class="red">*</span></label>
                                <div class="col-md-8">
                                    @Html.TextAreaFor(E => E.Description, new { @class = "form-control", @placeholder = "Description" })
                                    @Html.ValidationMessageFor(E => E.Description)
                                </div>
                            </div>


                            <div class="form-group btnShowDIv" id="sub">
                                <div class="col-md-12 text-center">
                                    <button type="submit" class="btn btn-primary" id="btnSubmit"> Submit</button>
                                    <a href='@Url.Action("Index")' class="btn btn-primary">Cancel</a>
                                </div>
                            </div>

                        </div>

                    </div>
                    </div>
                
            </div>
        </div>
    </div>
    </div>

    @section scripts{
        @Scripts.Render("~/bundles/jqueryval")
        <script src="~/Scripts/jquery-3.3.1.js"></script>
        <script src="~/Scripts/jquery-3.3.1.min.js"></script>
        <script type="text/javascript">

            $(document).ready(function () {
                $('#btnSubmit').click(function () {
                    if ($('#fileupload').val() == '') {

                        alert('Plase select file');

                        return;

                    }
                    var Data = [];
                    Data.push({
                        PK_ItemId: ($('#PK_ItemId').val() == '') ? 0 : $('#PK_ItemId').val(),
                        ItemName: $('#ItemName').val(),
                        OpeningQuantity: $('#OpeningQuantity').val(),
                        Description: $('#Description').val(),
                        CategoryName: $('#CategoryName').val(),
                        ItemPrice: $('#ItemPrice').val()

                    });

                    var strjson = JSON.stringify(Data);

                    var formdata = new FormData();

                    var file = $('#fileupload')[0];

                    formdata.append('ProductImage', file.files[0]);
                    formdata.append('ProductData', strjson);


                    $.ajax({

                        url: 'http://localhost:30575/api/Product/AddProductDetails',

                        type: 'POST',

                        data: formdata,

                        contentType: false,

                        processData: false,

                        success: function (data) {
                            alert(data.Message);
                            window.location.href = '@Url.Action("Index","Product")';

                        },

                        error: function () {

                        //    $('#updatepanelFile').addClass('alert_error').html('<strong>Failed!</strong> Error in upload');

                        }

                    })
                });


            });
        </script>
    }

Views/Product/Index.cshtml
@{
    ViewBag.Title = "Index";
}
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("Home", "Index", "Product", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Product", "Index", "Product")</li>
                <li>@Html.ActionLink("Store", "Index", "Store")</li>
                <li>@Html.ActionLink("Logout", "Index", "Home")</li>
            </ul>
        </div>
    </div>
</div>
<div class="section-body">
    <div class="container-fluid contentHeightShow">
        <div class="panel panel-default">
            <div class="panel-heading">
                <div class="textHead"><h2><strong>Product Stock</strong></h2></div>
                <div style="text-align:right">
                    <a class="btn btn-primary" href="@Url.Action("AddEditProduct")"><i class="fa fa-plus"></i>Add New</a>
                </div>

            </div>
            <div class="panel-body">
                @*<div class="row">
                        <div class="col-md-6 col-md-offset-3">
                            <div class="panel panel-default">
                                <div class="panel-heading">Peoduct Search</div>
                                <div class="panel-body">
                                    <div class="form-horizontal">
                                        <div class="form-group">
                                            <div class="col-md-6 col-sm-6">
                                                <select class="form-control" id="SearchCreteria">
                                                    <option selected="selected" value="">Select</option>
                                                    <option value="ItemName">Product Name</option>
                                                    <option value="Date">Created Date</option>

                                                </select>
                                            </div>
                                            <div class="col-md-6 col-sm-6">
                                                <div id="imaginary_container">
                                                    <div class="input-group stylish-input-group">
                                                        <input type="text" id="SearchValue" class="form-control" placeholder="Search">
                                                        <span class="input-group-addon">
                                                            <button type="submit" onclick="getProductDetails()">
                                                                <span class="glyphicon glyphicon-search"></span>
                                                            </button>
                                                        </span>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>*@


                <div id="GridDiv">
                    <div class="col-md-12">
                        <div id="table-scroll" class="table-scroll  table-responsive table-scroll-Onboard">
                            <table id="main-table" class="main-table  table-bordered table table-hover">
                                <thead>
                                    <tr>
                                        <th class="text-center">Sr.No.</th>
                                        <th class="text-center">Product Name</th>
                                        <th class="text-center">Product Price </th>
                                        <th class="text-center">Quantity</th>
                                        <th class="text-center">Product Category</th>
                                        <th class="text-center">Description</th>
                                        <th class="text-center">Action</th>

                                    </tr>
                                </thead>
                                <tbody id="tbodyProductDetails"></tbody>


                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@section scripts{
<script type="text/javascript">
    $(document).ready(function () {

        getProductDetails();

    });
    function getProductDetails() {
        var trHTML = '';
        $("#tbodyProductDetails").html('');
        $.ajax({
            url: 'http://localhost:30575/api/Product/GetItemDetalis?',
            type: 'GET',
            // data: { 'SearchBy': $('#SearchCreteria').val(), 'SearchValue': $('#SearchValue').val()},
            success: function (data) {
                //  alert(data)

                $.each(data, function (index, element) {
                    var pkid = element.PK_ItemId;
                    trHTML += '<tr>'
                        + '<td class="text-center">' + parseInt(index + 1) + '</td>'
                        + '<td class="text-center">' + element.ItemName + '</td>'
                        + '<td class="text-center">' + element.ItemPrice + '</td>'
                        + '<td class="text-center">' + element.OpeningQuantity + '</td>'
                        + '<td class="text-center">' + element.CategoryName + '</td>'
                        + '<td class="text-center">' + element.Description + '</td>'
                        + '<td class="text-center"><button class="btn - primary" onclick="EditDetails(' + pkid + ')" >Edit</button> <button class="btn - danger" onclick="DeleteDetails(' + pkid + ')" >Delete</button></td>'
                    //onclick = 'btnRouteSwap(" + tot + ", " + PK_RouteClubId + ", " + ele.PK_Employee_Id + ", " + ele.PK_Det_ClubId + ", " + ScottEnabled + ", " + CompanyId + ")'
                    //+ '<td class="text-center">' +<a class="btn btn-primary">Edit</a>+ '</td>'

                    '</tr>'
                });
                $("#tbodyProductDetails").append(trHTML);

                //$('#GridDiv').html(data);
            }
        });
    }
    function EditDetails(Id) {
        /**/
        window.location.href = "http://localhost:30575/Product/AddEditProduct?id="+Id
    /**/
    }

    function DeleteDetails(pkids) {
        var res = confirm('Are You Sure You Want To Delete Product.')
        if (res) {
            $.ajax({
                url: 'http://localhost:30575/api/Product/DeleteProduct?PK_ItemId=' + pkids,
                type: 'GET',
                success: function (data) {
                    alert(data.Message);
                    window.location.href = '@Url.Action("Index","Product")'

                }
            });
        }
    }
</script>
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @*<div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Home", "Index", "Product", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Logout", "Index", "Home")</li>
                </ul>
            </div>
        </div>
    </div>*@
    @*<div class="container body-content">*@
        @RenderBody()
    
        
    @*</div>*@

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>